### PR TITLE
Bind to legacy driver

### PR DESCRIPTION
**Pull request by vegar**
While we wait for the new mongo c# driver to get LINQ support, I have compiled MongoRepository against the legacy driver. 

The reason for this, is to be able to use both the new 2.0 api and MongoRepository in the same project with out getting into conflicts on mongo driver version.

### CODE REVIEW

**Comment by RobThree** [comment]
See my comment [here](https://github.com/RobThree/MongoRepository/issues/4#issuecomment-135430927).

**Comment by vegar** [comment]
All your comments are perfectly valid. 

We are in a situation where our project have gotten a little too much 'MongoRepository'-juice all over, and are looking for a way to move forward. Getting access to the new 2.0 aggregation-framework would help us much, but as it is, MongoRepository is kind of blocking the way. I'm in no way blaming you or MongoRepository for that. It gave us a great head-start early in the project, but we failed at isolating our data access from the rest of the application.

Anyway - this pull-request is sort of a 'do whatever takes us forward' with a heavy weight on _us_...

I'll look into the deprecated methods and replace the implementation where an alternative exist. 

For the net3.5/4.0.... As I understand, [Mongo have left <4.5 behind](http://docs.mongodb.org/ecosystem/drivers/csharp/).

**Comment by vegar** [comment]
I need to check that the new implementations of GetTotalDataSize() and GetTotalStorageSize() returns the same values as before. 

The `RequestStart` and `RequestDone` methods are still there, but are made internal. I'll need to spend some more time to see what the alternative would be, and why it was hidden in the first place.

**Comment by RobThree** [comment]
See https://github.com/RobThree/MongoRepository/issues/4

**Pull request closed without merging**
